# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170817_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activeLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(blank=True, to='projects.Tech'),
        ),
    ]
