# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170817_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
    ]
