# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tech',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='skill_level',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
