# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170819_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
