# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_tech_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['-skill_level']},
        ),
        migrations.AlterField(
            model_name='project',
            name='gitHubLink',
            field=models.URLField(blank=True),
        ),
    ]
