# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170819_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name']},
        ),
    ]
