# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170819_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
